name: 'tagging'

on:
  workflow_dispatch

jobs:
  testing:
    name: 'testing process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
      
    - name: git tag
      run : |
        echo "first command"
        git fetch --unshallow --tags
        sleep 5
        echo "second command"
        git tag -l
