name: 'test'
on:
  create:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: checking whether the tags are valid or not
        run: | 
         echo ${{ github.ref }} | awk -F '/' '{print $3}' > file2 
         sudo apt-get install -y dos2unix
         dos2unix shell.sh
         chmod 777 shell.sh
         ./shell.sh
