name: 'tagging-2'

on:
  create:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  testing:
    name: 'testing process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
      
    - name: git tag
      run : |
        echo "first command"
        git fetch --unshallow --tags
        sleep 5
        echo "second command"
        git tag -l
        sleep 5
        echo "tird command"
        echo github.ref
        sleep 5
        echo "4th command"
        echo ${{ github.ref }} | awk -F '/' {print $3} > file1
        cat file1
